M48
; DRILL file {KiCad 6.0.11-2627ca5db0~126~ubuntu22.04.1} date 2023年02月19日 20時28分19秒
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-19T20:28:19+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11-2627ca5db0~126~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0827
%
G90
G05
T1
X4.2421Y-5.3937
X4.4193Y-5.3937
T2
X4.3307Y-4.9803
T0
M30
